version: 2.1
jobs:
  build-and-test:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            pip install --upgrade pip
            pip install -r packages/requirements.txt
            export PYTHONPATH=./packages/titanic
            python packages/titanic/titanic/train_pipeline.py
            pytest -s packages/titanic/tests/

  build-docker-image:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Building Docker Image
          command: |
            docker build -t mattague/titanic .

  push-docker-image:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Pushing Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username=$DOCKERHUB_USERNAME --password-stdin
            docker push mattague/titanic


workflows:
  main:
    jobs:
      - build-and-test
      - build-docker-image
      - push-docker-image:
          requires:
            - build-and-test
            - build-docker-image
