version: 2.1
jobs:
  build-and-test:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            pip install --upgrade pip
            pip install -r packages/requirements.txt
            PYTHONPATH=./packages/titanic pytest -s packages/titanic/tests/

workflows:
  main:
    jobs:
      - build-and-test
